import { useRef, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import useAdminQueryRead from './useAdminQueryRead';
import useAdminQueryWrite from './useAdminQueryWrite';

export default function useAdminQuerySync({
  isAdmin,
  activeTab,
  setActiveTab,
  search,
  setSearch,
  playersSearch,
  setPlayersSearch,
  playersPage,
  setPlayersPage,
  playersLimit,
  setPlayersLimit,
  playersSortBy,
  setPlayersSortBy,
  playersSortDir,
  setPlayersSortDir,
  selectedPlayerId,
  setSelectedPlayerId,
  supportTab,
  setSupportTab,
  supportStatus,
  setSupportStatus,
  supportSearch,
  setSupportSearch,
  supportCategory,
  setSupportCategory,
  supportPage,
  setSupportPage,
  supportLimit,
  setSupportLimit,
  supportSortDir,
  setSupportSortDir,
  selectedTicketId,
  setSelectedTicketId,
  logsSearch,
  setLogsSearch,
  logsActionType,
  setLogsActionType,
  logsTargetTable,
  setLogsTargetTable,
  logsUserId,
  setLogsUserId,
  logsPage,
  setLogsPage,
  logsLimit,
  setLogsLimit,
  logsSortDir,
  setLogsSortDir,
  setLogsPrefetched,
  endgameTab,
  setEndgameTab,
  normalizeText,
  normalizeSortDir,
  clampInt,
}) {
  const [searchParams, setSearchParams] = useSearchParams();
  const searchParamsKey = searchParams.toString();
  const lastSyncedParamsKeyRef = useRef('');
  const ignoreNextUrlSyncRef = useRef(false);
  const [urlHydrated, setUrlHydrated] = useState(false);

  useAdminQueryRead({
    isAdmin,
    activeTab,
    supportTab,
    searchParams,
    searchParamsKey,
    lastSyncedParamsKeyRef,
    ignoreNextUrlSyncRef,
    setUrlHydrated,
    setActiveTab,
    setSearch,
    setPlayersSearch,
    setPlayersPage,
    setPlayersLimit,
    setPlayersSortBy,
    setPlayersSortDir,
    setSelectedPlayerId,
    setSupportTab,
    setSupportStatus,
    setSupportSearch,
    setSupportCategory,
    setSupportPage,
    setSupportLimit,
    setSupportSortDir,
    setSelectedTicketId,
    setLogsActionType,
    setLogsTargetTable,
    setLogsUserId,
    setLogsPage,
    setLogsLimit,
    setLogsSortDir,
    setLogsSearch,
    setLogsPrefetched,
    setEndgameTab,
    normalizeSortDir,
    clampInt,
  });

  useAdminQueryWrite({
    isAdmin,
    urlHydrated,
    activeTab,
    search,
    playersSearch,
    playersPage,
    playersLimit,
    playersSortBy,
    playersSortDir,
    selectedPlayerId,
    supportTab,
    supportStatus,
    supportSearch,
    supportCategory,
    supportPage,
    supportLimit,
    supportSortDir,
    selectedTicketId,
    logsSearch,
    logsActionType,
    logsTargetTable,
    logsUserId,
    logsPage,
    logsLimit,
    logsSortDir,
    endgameTab,
    searchParamsKey,
    setSearchParams,
    lastSyncedParamsKeyRef,
    ignoreNextUrlSyncRef,
    normalizeText,
  });
}
